# Generated by Django 2.1.5 on 2020-05-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='selection_cnt',
            new_name='selection_count',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='selection_lim',
            new_name='selection_limit',
        ),
    ]
