# Generated by Django 2.1.5 on 2020-05-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200509_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='opt_name',
            new_name='option_name',
        ),
    ]
