# Generated by Django 2.1.5 on 2020-05-09 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200509_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='selection_limit',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
