# Generated by Django 2.1.5 on 2020-05-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200509_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_name',
            field=models.CharField(default='Selection(s)', max_length=32),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, default=999.99, max_digits=5),
        ),
    ]
